### ISSUE TITLE
Rails 5.0: undefined method `hidden_actions'

### ISSUE THREAD

**Issue by Nowaker** [hcatlin/make_resourceful#18]
After upgrading from Rails 4.2.x to 5.0.x, I've encountered this problem with `make_resourceful`:

```
ActionController::RoutingError (undefined method `hidden_actions' for SitesController:Class):

/home/nowaker/.rvm/gems/ruby-2.6.3/bundler/gems/make_resourceful-787e73272fe4/lib/resourceful/builder.rb:54:in `apply'
/home/nowaker/.rvm/gems/ruby-2.6.3/bundler/gems/make_resourceful-787e73272fe4/lib/resourceful/maker.rb:69:in `make_resourceful'
app/controllers/sites_controller.rb:5:in `<class:SitesController>'
```

**Comment by Nowaker** [comment]
Uncommenting this line resolves the problem:
```ruby
kontroller.hidden_actions.reject! &@ok_actions.method(:include?)
```

I suggest changing it to:
```
if kontroller.respond_to?(:hidden_actions) 
  kontroller.hidden_actions.reject! &@ok_actions.method(:include?)
end
```

This is because Rails 5+ no longer has a notion of "hidden actions".

**Comment by Nowaker** [comment]
https://github.com/hcatlin/make_resourceful/pull/19

**Comment by Nowaker** [comment]
Fixed in https://github.com/HamptonMakes/make_resourceful/pull/19
